name: Windows CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
#    - uses: numworks/setup-msys2@v1
    - name: Try MSYS2
      run: |
        bash -l -c "uname -a"
        bash -l -c "pwd"
        bash -l -c "echo $PATH"
        bash -l -c "find / -name pacman -print"
#        bash -l -c "/usr/bin/pacman -S mingw-w64-x86_64-gtk3"
#        msys2do pacman -S mingw-w64-x86_64-glade
#        msys2do pacman -S mingw-w64-x86_64-python3-gobject
#        cd src/generate-executable/_cx_freeze
#        msys2do python setup.py bdist_msi
